host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""
lang: "en-US"

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# SEO
# -------------------
title: Minutes to Midnight
tagline: Music producers and sound designers
description: Digital polymaths, we master the art of sound design, production and writing music since the 1990s.
permalink: /blog/:title/
keywords:
  minutes to midnight,
  simone silvestroni,
  emilio albertoni,
  sound design,
  bass player,
  game audio,
  music production,
  concept album,
  mixing,
  mastering,
  reaper,
  pro tools,
  logic pro x,
timezone: Europe/Berlin
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: simone@minutestomidnight.co.uk

# -------------------
# Brand
# -------------------
brand:
  m2m_intro: 'Digital polymaths, we master the art of sound design, production and writing music since the 1990s.'

# -------------------
# Exclusions
# -------------------
exclude:
  - README.md

# -------------------
# Inclusions
# -------------------
include: ["_pages", "_redirects"]

# -------------------
# Defaults
# -------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "musicproduction"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "sounddesign"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "gameaudio"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "newsletter"
    values:
      layout: "newsletter"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# -------------------
# Collections
# -------------------
collections:
  music:
    output: true
    permalink: /work/music/:path/
  musicproduction:
    output: true
    permalink: /work/music-production/:path/
  sounddesign:
    output: true
    permalink: /work/sound-design/:path/
  gameaudio:
    output: true
    permalink: /work/game-audio/:path/
  newsletter:
    output: true
    permalink: /newsletter/archive/:path/
  notes:
    output: true
    permalink: /note/:path/

# -------------------
# Archives
# -------------------
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: cats-tags
  permalinks:
    category: '/blog/category/:name/'
    tag: '/blog/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# -------------------
# Responsive images
# -------------------
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
      quality: 80
    - width: 768
      quality: 80
    - width: 992
      quality: 80
    - width: 1200
      quality: 85
  strip: true
  output_path_format: assets/images/responsive/%{width}/%{basename}

# -------------------
# Plugins
# -------------------
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image

# -------------------
# Work endorsements
# -------------------
endorsements:
  audio:
    - name: 'Jean-Claude Nouchy'
      role: 'FX Supervisor at Scanline VFX'
      url: 'https://www.linkedin.com/in/jcn-visualcortexlab/'
      quote: 'When passion goes beyond working duties... here’s Simone. Addiction and reliability are two great details you cant easily find nowadays in a professional and he gets both.'
    - name: 'Christopher Carvalho'
      role: 'Founder at Unlock Your Sound'
      url: 'https://unlockyoursound.com/'
      quote: 'What’s always impressed me about Simone is his attention to detail, which he demonstrates in every area of his work. Not only is he a prolific producer and bassist, but he easily comprehends and executes on the most abstract concepts across tech, audio, marketing, branding, and visual arts. When you work with Simone, everything is down, documented, and organised, which makes it very easy to work with him directly or in the context of a team.'
    - name: 'Chris Pavey'
      role: 'Mastering engineer at CPM'
      url: 'https://www.linkedin.com/in/chris-pavey-12034559/'
      quote: 'Simone is a gifted musician, producer and all round creative, with every project we have worked on being greatly improved by his talents. Impressive technical proficiency with various DAWs (ProTools, Wavelab, RX) as well as the creative knowledge to craft with them what ever is required for the project. When working with Simone, his precise and detailed manor make him an excellent addition to any project or team.'

# -------------------
# Work certifications
# -------------------
certifications:
  sound:
    - name: 'Berklee College Of Music'
      href: 'https://www.berklee.edu/'
      desc: '(audio master engineering, music production, electric bass), 2011-2016'
    - name: 'Apple Pro Certified'
      href: 'https://training.apple.com/us/en/recognition'
      desc: 'Logic Pro X 10.3, London, 2018'
    - name: 'Game Developer Conference'
      href: 'https://www.gdconf.com/'
      desc: 'San Jose (California), 2002'
    - name: 'Game Audio Network Guild'
      href: 'https://www.audiogang.org/'
      desc: 'bronze member, San Jose (California), 2002'
    - name: 'Centro Professione Musica'
      href: 'https://www.cpm.it/corsi-musica-milano'
      desc: 'diploma (bass, music theory, harmony &amp; arrangement), Milan, 1993-1995'

# -------------------
# Publications
# -------------------
pubs:
  - title: 'A trip to freedom from Berlin to Berlin'
    excerpt: 'A real-life story of imprisonment and liberty, between two wars and three generations.'
    url: 'https://medium.com/lessons-from-history/a-trip-to-freedom-from-berlin-to-berlin-e9725231eb2e'
    featimage: true