# -------------------
# Main
# -------------------
host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""
lang: "en-GB"

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# Configuration
# -------------------
title: Minutes to Midnight
tagline: Sound designer, game audio pioneer
description: 'Sound designer, bassist and music producer'
aboutshort: 'I document thoughts, opinions, and how I work with technology to translate ideas into an enjoyable experience.'
aboutlong: 'Pioneering game audio in the early 2000s, I specialised in mixing and mastering, while honing and updating my sound design skills.'
permalink: /blog/:title/
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass,
  game audio,
  foley,
  field recording,
  music production,
  music composer,
  mix,
  master,
  reaper,
  pro tools,
  logic pro x,
timezone: Europe/Berlin
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: hello@minutestomidnight.co.uk
mastodon:
  instance: sonomu.club
  username: m2m
kramdown:
  syntax_highlighter_opts:
    disable: true

# -------------------
# Exclusions
# -------------------
exclude:
  - README.md

# -------------------
# Inclusions
# -------------------
include: ["_pages", "_redirects", ".well-known"]

# -------------------
# Defaults
# -------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# -------------------
# Collections
# -------------------
collections:
  notes:
    output: true
    permalink: /notes/:path/

# -------------------
# Archives
# -------------------
jekyll-archives:
  enabled:
    - tags
  layout: tags
  permalinks:
    tag: '/blog/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# -------------------
# Plugins
# -------------------
plugins:
  - jekyll-archives