# -------------------
# Main
# -------------------
host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""
lang: "en-GB"

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# Configuration
# -------------------
title: Minutes to Midnight
tagline: Music producer and sound designer
description: 'Sound designer, bassist and music producer'
shortabout: 'I’m a polymath focused on high-quality digital productions since 1992.'
permalink: /blog/:title/
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass,
  game audio,
  foley,
  field recording,
  music production,
  music composer,
  mix,
  master,
  reaper,
  pro tools,
  logic pro x,
timezone: Europe/Berlin
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: hello@minutestomidnight.co.uk
mastodon:
  instance: indieweb.social
  username: m2m
kramdown:
  syntax_highlighter_opts:
    disable: true

# -------------------
# Exclusions
# -------------------
exclude:
  - README.md

# -------------------
# Inclusions
# -------------------
include: ["_pages", "_redirects", ".well-known"]

# -------------------
# Defaults
# -------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# -------------------
# Collections
# -------------------
collections:
  notes:
    output: true
    permalink: /notes/:path/

# -------------------
# Archives
# -------------------
jekyll-archives:
  enabled:
    - tags
  layout: tags
  permalinks:
    tag: '/blog/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# -------------------
# Plugins
# -------------------
plugins:
  - jekyll-archives

# -------------------
# Main skills
# -------------------
mainSkills:
  - name: 'Bass'
    url: '/blog/tag/bass/'
  - name: 'Mixing'
    url: '/blog/tag/mix/'
  - name: 'Sound design'
    url: '/blog/tag/sound-design/'
  - name: 'Game audio'
    url: '/blog/tag/video-game/'
  - name: 'Mastering'
    url: '/blog/tag/master/'

completeSkills:
  - name: 'recording'
  - name: 'field recording'
  - name: 'editing'
  - name: 'Foley'
  - name: 'game audio integration (Wwise)'
  - name: 'web development'

# -------------------
# Work endorsements
# -------------------
endorsements:
  - name: 'Jean-Claude Nouchy'
    role: 'FX Supervisor at Scanline VFX'
    url: 'https://www.imdb.com/name/nm2327167/'
    quote: 'When passion goes beyond working duties... here’s Simone. Addiction and reliability are two great details you can’t easily find nowadays in a professional, and he gets both.'
  - name: 'Leland Sklar'
    role: 'Bass player for Toto and Phil Collins'
    url: 'https://en.wikipedia.org/wiki/Leland_Sklar'
    quote: 'I’m really digging this one. The style reminds me of Paul Webb from Talk Talk. No needless notes. Great tone and feel. Good work.'
  - name: 'Gerald Duchene'
    role: 'Music composer, founder of Antiquity Music'
    url: 'https://antiquitysessions1.bandcamp.com'
    quote: 'I’ve worked with Simone on both my projects and his and the professionalism and quality of his work is world class. I have rarely had to give direction and he takes direction like an interested pro. I’m very partial to his style and tone. I hope to be still playing with him in the years to come. If you want a bass track that stands out and makes people sit up and listen, Simone is your man.'
  - name: 'Christopher Carvalho'
    role: 'Artist manager, Unlock Your Sound'
    url: 'https://unlockyoursound.com/'
    quote: 'What’s always impressed me about Simone is his attention to detail, which he demonstrates in every area of his work. Not only is he a prolific producer and bassist, but he easily comprehends and executes on the most abstract concepts across tech, audio, marketing, branding, and visual arts. When you work with Simone, everything is down, documented, and organised, which makes it very easy to work with him directly or in the context of a team.'
  - name: 'Callum Gardner'
    role: 'Singer-songwriter'
    url: 'https://callumgardnerofficial.com'
    quote: 'Incredibly versatile bass player, producer & composer - I strongly recommend working with Minutes to Midnight after many successful years of gigging, recording, writing & rehearsing together in various projects.'
  - name: 'Chris Pavey'
    role: 'Mastering engineer, CPM'
    url: 'https://www.linkedin.com/in/chris-pavey-12034559/'
    quote: 'Simone is a gifted musician, producer and all round creative, with every project we have worked on being greatly improved by his talents. Impressive technical proficiency with various DAWs (ProTools, Wavelab, RX) as well as the creative knowledge to craft with them what ever is required for the project. When working with Simone, his precise and detailed manor make him an excellent addition to any project or team.'
  - name: 'Martin Wykes'
    role: 'Music composer and producer'
    url: 'https://soundbetter.com/profiles/174278-martin-wykes'
    quote: 'Simone, is a wonderful bass player and an absolute professional to work with. He does exactly what he says on the tin and delivers musical and imaginative bass lines that help make the track shine. He is extremely detailed and musical and he definitely brings a style of his own to the project which made the song better. He also has an absolute pro sound that fits right into a mix. Just brilliant.'