host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""
lang: "en-US"

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# SEO
# -------------------
title: Minutes to Midnight
tagline: Sound and Web Designer
description: I create and produce sound and music across multiple media and make websites using Jekyll or WordPress. Professional bass player, composer and field recordist.
permalink: /blog/:title/
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass player,
  game audio,
  music production,
  concept album,
  mixing,
  mastering,
  reaper,
  pro tools,
  logic pro x,
  web design,
  web development,
  front-end,
  jekyll,
  jamstack,
  sass
timezone: Europe/Rome
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: contact@minutestomidnight.co.uk

# -------------------
# Brand
# -------------------
brand:
  m2m_pitch: 'I’m Simone Silvestroni,<br>a digital polymath<br>between sound and web design'
  m2m_intro: 'I create and produce sound and music across multiple media and make websites using Jekyll or WordPress. I started working in the publishing industry in 1994 and transitioned to web design a year later, becoming an expert in web standards. I’m also a professional bass player, a composer and a field recordist.'

# -------------------
# Exclusions
# -------------------
exclude:
  - node_modules/
  - sass/
  - README.md
  - package.json
  - package-lock.json

# -------------------
# Inclusions
# -------------------
include: ["_pages", "_redirects"]

# -------------------
# Defaults
# -------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "sounddesign"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "newsletter"
    values:
      layout: "newsletter"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "webdesign"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "project"

# -------------------
# Collections
# -------------------
collections:
  sounddesign:
    output: true
    permalink: /projects/sound-design/:path/
  webdesign:
    output: true
    permalink: /projects/web-design/:path/
  music:
    output: true
    permalink: /music/:path/
  newsletter:
    output: true
    permalink: /newsletter/archive/:path/
  notes:
    output: true
    permalink: /note/:path/

# -------------------
# Archives
# -------------------
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: cats-tags
  permalinks:
    category: '/blog/category/:name/'
    tag: '/blog/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# -------------------
# Responsive images
# -------------------
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
      quality: 80
    - width: 768
      quality: 80
    - width: 992
      quality: 80
    - width: 1200
      quality: 85
  strip: true
  output_path_format: assets/images/responsive/%{width}/%{basename}

# -------------------
# Plugins
# -------------------
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image

# -------------------
# Work endorsements
# -------------------
endorsements:
  web:
    - name: 'Neil Kenneth Palmer'
      role: 'VP of product development at C6 Marketing'
      url: 'https://www.linkedin.com/in/neil-k-palmer/'
      quote: 'Simply put, Simone is one of the finest, and most passionate front-end developers that I have every come across. His knowledge on UI and UX is vast and combine this with his front-end development skills, he is one of the finest front end developers out there. It was a pleasure to manage and work with Simone and I hope to get the chance again in the future.'
    - name: 'Michelle Anderson'
      role: 'staff engineer at Deliveroo'
      url: 'https://www.linkedin.com/in/michelledangeranderson/'
      quote: 'Simone was an integral member of our team. His passion for the web and careful and persistent work ethic meant that he delivered consistently above expectations. His initiative is impressive. His experience makes him an expert in his field; has a firm understanding of front end web. With his sharp sense of humor, he would make a wonderful addition to any web team!'
    - name: 'Gabriele Rosati'
      role: 'UX and interaction design manager at UniCredit'
      url: 'https://www.linkedin.com/in/rosati/'
      quote: 'My experience of working with Simone has always been very positive and enjoyable. Simone always takes a pragmatic and investigative approach to finding solutions for our needs and has very friendly and helpful attitude. His attention to detail makes him always deliver perfect coded products, saving us time and concerns on the web projects he develops.'
  audio:
    - name: 'Jean-Claude Nouchy'
      role: 'FX Supervisor at Scanline VFX'
      url: 'https://www.linkedin.com/in/jcn-visualcortexlab/'
      quote: 'When passion goes beyond working duties... here’s Simone. Addiction and reliability are two great details you cant easily find nowadays in a professional and he gets both.'
    - name: 'Christopher Carvalho'
      role: 'Founder at Unlock Your Sound'
      url: 'https://unlockyoursound.com/'
      quote: 'What’s always impressed me about Simone is his attention to detail, which he demonstrates in every area of his work. Not only is he a prolific producer and bassist, but he easily comprehends and executes on the most abstract concepts across tech, audio, marketing, branding, and visual arts. When you work with Simone, everything is down, documented, and organised, which makes it very easy to work with him directly or in the context of a team.'
    - name: 'Chris Pavey'
      role: 'Mastering engineer at CPM'
      url: 'https://www.linkedin.com/in/chris-pavey-12034559/'
      quote: 'Simone is a gifted musician, producer and all round creative, with every project we have worked on being greatly improved by his talents. Impressive technical proficiency with various DAWs (ProTools, Wavelab, RX) as well as the creative knowledge to craft with them what ever is required for the project. When working with Simone, his precise and detailed manor make him an excellent addition to any project or team.'

# -------------------
# Work certifications
# -------------------
certifications:
  sound:
    - name: 'Berklee College Of Music'
      href: 'https://www.berklee.edu/'
      desc: '(audio master engineering, music production, electric bass), 2011-2016'
    - name: 'Apple Pro Certified'
      href: 'https://training.apple.com/us/en/recognition'
      desc: 'Logic Pro X 10.3, London, 2018'
    - name: 'Game Developer Conference'
      href: 'https://www.gdconf.com/'
      desc: 'San Jose (California), 2002'
    - name: 'Game Audio Network Guild'
      href: 'https://www.audiogang.org/'
      desc: 'bronze member, San Jose (California), 2002'
    - name: 'Centro Professione Musica'
      href: 'https://www.cpm.it/corsi-musica-milano'
      desc: 'diploma (bass, music theory, harmony &amp; arrangement), Milan, 1993-1995'
  web:
    - name: 'Member of <a href="https://iwanet.org/">IWA</a>'
    - name: 'Nielsen Norman Group UX Conference, 2010, London'
    - name: 'PHP development course by HTML.IT, 2009, Milan'

# -------------------
# Publications
# -------------------
pubs:
  - title: 'A trip to freedom from Berlin To Berlin'
    excerpt: 'A real-life story of imprisonment and liberty, between two wars and three generations.'
    url: 'https://medium.com/lessons-from-history/a-trip-to-freedom-from-berlin-to-berlin-e9725231eb2e'
    featimage: true
  - title: 'A modern workflow for the multi-device web'
    excerpt: 'A process analysis that has led UI Farm Ltd to their workflow for delivering modern web solutions.'
    url: 'https://medium.com/ui-farm/how-we-work-a-modern-workflow-for-the-multi-device-web-4e0dcb081b5b'
    featimage: true