# -------------------
# Site settings
# -------------------
host: 'localhost'
url: 'https://minutestomidnight.co.uk'
baseurl: ''
lang: 'en-GB'
title: 'Minutes to Midnight'
tagline: 'Web designer & music producer'
timezone: Europe/London
logo: '/assets/images/m2m-og-image.png'
typeface: 'Crimson Pro, Schibsted Grotesk'
typeface-preload: 'schibstedgrotesk-regular.woff2'
jekyll-version: '4.3.3'

# -------------------
# Personal data
# -------------------
author:
  name: 'Simone Silvestroni'
  givenName: 'Simone'
  familyName: 'Silvestroni'
  email: 'hello@minutestomidnight.co.uk'
mastodon:
  instance: sonomu.club
  username: m2m

# -------------------
# Online profiles
# -------------------
link:
  - name: Email
    label: hello@minutestomidnight.co.uk
    url: mailto:hello@minutestomidnight.co.uk
  - name: GitHub
    label: https://github.com/simonesilvestroni
    url: https://github.com/simonesilvestroni
  - name: LinkedIn
    label: https://www.linkedin.com/in/simonesilvestroni
    url: https://www.linkedin.com/in/simonesilvestroni
  - name: Bandcamp
    label: https://minutestomidnight.bandcamp.com
    url: https://minutestomidnight.bandcamp.com
  - name: YouTube
    label: https://www.youtube.com/@m2m
    url: https://www.youtube.com/@m2m

# -------------------
# About
# -------------------
description: "My name is <a rel='me' class='u-url' href='/about/'><span class='p-name'>Simone Silvestroni</span></a>. A gen X with a straight to the point attitude, I use a mix of instinct and academic learning to juggle between art and technology in equal measure. Based in Cambridge, I work in <a class='highlight' href='/sound-design/'>sound production</a> and <a class='highlight' href='/web-design/'>web design</a> under the moniker <em>Minutes to Midnight</em>."
intro: "Based in Cambridge, I work in <a href='/web-design/'><mark>web design</mark></a> and <a href='/sound-design/'><mark>sound production</mark></a> under the moniker <em>Minutes to Midnight</em>."
indepth: "My name is <a href='/about/'>Simone Silvestroni</a>. A gen X with a straight to the point attitude, I use a mix of instinct and academic learning to juggle between art and technology in equal measure."
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass,
  game audio,
  foley,
  field recording,
  music production,
  music composer,
  mix,
  master,
  reaper,
  pro tools,
  logic pro,
  web design,
  web development,
  web performance,
  web accessibility,
  web usability,
  front-end,
  ux,
  user experience,
  jekyll,
  wordpress,
  html,
  css

# -------------------
# Inclusions
# -------------------
include: ["_pages"]

# -------------------
# SASS
# -------------------
sass:
  sass_dir: /assets/css/partials/
  sourcemap: development

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# Markdown
# -------------------
kramdown:
  syntax_highlighter_opts:
    disable: true

# -------------------
# Jekyll defaults
# -------------------
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# -------------------
# Jekyll collections
# -------------------
collections:
  notes:
    output: true
    permalink: /notes/:path/

# -------------------
# Jekyll archives
# -------------------
jekyll-archives:
  enabled:
    - tags
  layout: tags
  permalinks:
    tag: '/blog/tag/:name/'
  slug_mode: latin

# -------------------
# Markdown
# -------------------
kramdown:
  syntax_highlighter_opts:
    disable: true

# -------------------
# Jekyll plugins
# -------------------
plugins:
  - jekyll-archives