host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""

# Feeds
feed:
  posts_limit: 30

# SEO
title: Minutes to Midnight
tagline: Sound and Web Designer
description: Minutes to Midnight is the moniker of Simone Silvestroni. A digital polymath, I’ve been working as a sound and web designer for more than 25 years.
permalink: /blog/:title/
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass player,
  game audio,
  music production,
  mixing,
  mastering,
  reaper,
  pro tools,
  logic pro x,
  web design,
  web development,
  front-end,
  jekyll,
  sass
timezone: Europe/Rome
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: contact@minutestomidnight.co.uk

# Brand
brand:
  m2m_pitch: I&rsquo;m a liaison between creativity and logic.

# Work endorsements
endorsements:
  web:
    - name: 'Neil Kenneth Palmer'
      role: 'vice president of product development at C6 Marketing'
      url: 'https://www.linkedin.com/in/neil-k-palmer/'
      quote: 'Simply put, Simone is one of the finest, and most passionate front-end developers that I have every come across. His knowledge on UI and UX is vast and combine this with his front-end development skills, he is one of the finest front end developers out there. It was a pleasure to manage and work with Simone and I hope to get the chance again in the future.'
    - name: 'Michelle Anderson'
      role: 'staff engineer at Deliveroo'
      url: 'https://www.linkedin.com/in/michelledangeranderson/'
      quote: 'Simone was an integral member of our team. His passion for the web and careful and persistent work ethic meant that he delivered consistently above expectations. His initiative is impressive. His experience makes him an expert in his field; has a firm understanding of front end web. With his sharp sense of humor, he would make a wonderful addition to any web team!'
    - name: 'Alessandra Farabegoli'
      role: 'Digital Strategist'
      url: 'https://www.linkedin.com/in/alebegoli/'
      quote: 'Simone loves standards and usability, and he combines creativity and logic, a rare gift in the same person. He is competent and reliable, and he can work very well in a team.'

resume:
  web:
    - year: '1993'
      description: 'Started out as a proofreader, later evolved to desktop publisher learning the craft with renown editor Paola Varani for <em>RCS (Rizzoli)</em>.'
    - year: '1998'
      description: 'Deployed the first official website of a well-known historic <a href="https://web.archive.org/web/20010808100700/http://fc.retecivica.milano.it/rcmweb/libdonne/">feminist bookstore in Milan</a>.'
    - year: '2000-2005'
      description: 'Designed and developed my <a href="https://web.archive.org/web/20031208185857/http://www.playstos.com:80/index.html">game company’s website</a>.'
    - year: '2005-2007'
      description: 'Freelancing as a web designer and sound designer in Milan.'
    - year: '2007-2011'
      description: 'Landed a permanent job as a front-end developer for a company now part of <em>Accenture</em>, working for massive clients such as <em>UniCredit</em>.'
    - year: '2011'
      description: 'Moved to the UK after being hired for the same role by the online gaming company <em>Bodog</em> in London.'
    - year: '2012-2017'
      description: '<a href="https://web.archive.org/web/20161021065339/http://uifarm.co.uk/team/">Co-founded</a> the web firm <em>UI Farm</em> in London. We designed, developed and deployed advanced multi-device solutions for small to large companies, including <em>Reevoo</em>, <em>Not On The High Street</em>, <em>UniCredit</em> and <em>Elite Model Management (New York)</em>.'
    - year: '2017-today'
      description: 'Kick-started <em>Minutes to Midnight</em> in Cambridge. Embracing my wider skill set, I focused on both audio and web design.'

# Work certifications
certifications:
  sound:
    - name: 'Berklee College Of Music'
      href: 'https://www.berklee.edu/'
      desc: '(audio master engineering, music production, electric bass), 2011-2016'
    - name: 'Apple Pro Certified'
      href: 'https://training.apple.com/us/en/recognition'
      desc: 'Logic Pro X 10.3, London, 2018'
    - name: 'Game Developer Conference'
      href: 'https://www.gdconf.com/'
      desc: 'San Jose (California), 2002'
    - name: 'Game Audio Network Guild'
      href: 'https://www.audiogang.org/'
      desc: 'bronze member, San Jose (California), 2002'
    - name: 'Centro Professione Musica'
      href: 'https://www.cpm.it/corsi-musica-milano'
      desc: 'diploma (bass, music theory, harmony &amp; arrangement), Milan, 1993-1995'
  web:
    - name: 'Member of <a href="https://iwanet.org/">IWA</a>'
    - name: 'Nielsen Norman Group UX Conference, 2010, London'
    - name: 'PHP development course by HTML.IT, 2009, Milan'

exclude:
  - node_modules/
  - sass/
  - README.md
  - package.json
  - package-lock.json

include: ["_pages", "_redirects"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "webdesign"
    values:
      layout: "casestudy"
  - scope:
      path: ""
      type: "sounddesign"
    values:
      layout: "casestudy"

# Collections
collections:
  sounddesign:
    output: true
    permalink: /work/sound-design/:path/
  webdesign:
    output: true
    permalink: /work/web-design/:path/

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: cats-tags
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# Responsive images
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
      quality: 80
    - width: 768
      quality: 80
    - width: 1200
      quality: 90
  strip: true
  output_path_format: assets/images/responsive/%{width}/%{basename}

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image