# -------------------
# Site settings
# -------------------
host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""
lang: "en-GB"
title: Minutes to Midnight
tagline: Sound designer, game audio pioneer
permalink: /blog/:title/
timezone: Europe/London
logo: /assets/images/m2m-og-image.png

# -------------------
# Personal data
# -------------------
author:
  name: Simone Silvestroni
  email: hello@minutestomidnight.co.uk
mastodon:
  instance: sonomu.club
  username: m2m

# -------------------
# About
# -------------------
description: 'Sound designer, bassist and web designer'
who: "My name is <a rel='me' class='u-url' href='/about/'><span class='p-name'>Simone Silvestroni</span></a>. A gen X with a straight to the point attitude, I use a mix of instinct and academic learning to juggle between art and technology in equal measure. Based in Cambridge, I work in <a class='highlight' href='/web-design/'>web design</a> and <a class='highlight' href='/sound-design/'>sound production</a> under the moniker <em>Minutes to Midnight</em>."
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass,
  game audio,
  foley,
  field recording,
  music production,
  music composer,
  mix,
  master,
  reaper,
  pro tools,
  logic pro,
  web design,
  web development,
  web accessibility,
  web usability

# -------------------
# Inclusions
# -------------------
include: ["_pages"]

# -------------------
# SASS
# -------------------
sass:
  sass_dir: /assets/css/partials/
  sourcemap: development

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# Markdown
# -------------------
kramdown:
  syntax_highlighter_opts:
    disable: true

# -------------------
# Jekyll defaults
# -------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# -------------------
# Jekyll collections
# -------------------
collections:
  notes:
    output: true
    permalink: /notes/:path/

# -------------------
# Jekyll archives
# -------------------
jekyll-archives:
  enabled:
    - tags
  layout: tags
  permalinks:
    tag: '/blog/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# -------------------
# Jekyll plugins
# -------------------
plugins:
  - jekyll-archives