host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""

# SEO
title: Minutes to Midnight
tagline: Sound and Web Designer
description: Minutes to Midnight is the moniker of music producer and frontend developer Simone Silvestroni.
permalink: /blog/:title/
keywords:
  sound design,
  bass player,
  game audio,
  music production,
  web design,
  web development,
  frontend
timezone: Europe/Rome
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: hello@minutestomidnight.co.uk

# Brand
brand:
  m2m_pitch: I&rsquo;m a liaison between creativity and logic.

# Work certifications
certifications:
  sound:
    - name: 'Berklee College Of Music'
      href: 'https://www.berklee.edu/'
      desc: '(audio master engineering, music production, electric bass), 2011-2016'
    - name: 'Apple Pro Certified'
      href: 'https://training.apple.com/us/en/recognition'
      desc: 'Logic Pro X 10.3, London, 2018'
    - name: 'Game Developer Conference'
      href: 'https://www.gdconf.com/'
      desc: 'San Jose (California), 2002'
    - name: 'Game Audio Network Guild'
      href: 'https://www.audiogang.org/'
      desc: 'bronze member, San Jose (California), 2002'
    - name: 'Centro Professione Musica'
      href: 'https://www.cpm.it/corsi-musica-milano'
      desc: 'diploma (bass, music theory, harmony &amp; arrangement), Milan, 1993-1995'
  web:
    - name: 'Member of <a href="https://iwanet.org/">IWA</a>'
    - name: 'Nielsen Norman Group UX Conference, 2010, London'
    - name: 'PHP development course by HTML.IT, 2009, Milan'

exclude: 
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - build
  - js
  - sass
include: ["_pages", "_redirects"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "webdesign"
    values:
      layout: "casestudy"
  - scope:
      path: ""
      type: "sounddesign"
    values:
      layout: "casestudy"
  - scope:
      path: ""
      type: "originalmusicproductions"
    values:
      layout: "casestudy"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# Collections
collections:
  originalmusicproductions:
    output: true
    permalink: /work/original-music-productions/:path/
  sounddesign:
    output: true
    permalink: /work/sound-design/:path/
  webdesign:
    output: true
    permalink: /work/web-design/:path/
  notes:
    output: true
    permalink: /notes/:path/

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: cats-tags
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
  slug_mode: latin

excerpt_separator: <!--more-->

# Responsive images
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
    - width: 768
    - width: 1200

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image