host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""

# SEO
title: Minutes to Midnight
tagline: Sound and Web Designer
description: Minutes to Midnight is the moniker of music producer and frontend developer Simone Silvestroni.
permalink: /blog/:title/
keywords:
  sound design,
  bass player,
  game audio,
  music production,
  web design,
  web development,
  frontend
timezone: Europe/Rome
logo: /assets/images/silviamaggi-og-image.jpg
author:
  name: Simone Silvestroni
  email: hello@minutestomidnight.co.uk

# Brand
brand:
  m2m_avatar_src: /assets/images/minutestomidnight-avatar.jpg
  m2m_tagline: Hi, Simone here
  m2m_pitch: I&rsquo;m a liaison between creativity and logic.
  m2m_latestposts_limit: 2

# Skill set
skills-audio:
  - skill: mixing
  - skill: mastering
  - skill: foley
  - skill: field recording
  - skill: arrangement
  - skill: audio signal flow
  - skill: microphones
  - skill: dialogue and vocals
  - skill: editing
  - skill: audio restoration
  - skill: sound effects
  - skill: wwise
  - skill: fmod
  - skill: alienbrain
  - skill: instrumentalist
  - skill: drum programming
  - skill: drum replacement
  - skill: composition
  - skill: scoring
skills-web:
  - skill: jekyll
  - skill: liquid
  - skill: markdown
  - skill: HTML 5
  - skill: CSS 3
  - skill: SASS
  - skill: accessibility
  - skill: usability
  - skill: UX
  - skill: UI
  - skill: problem solving
  - skill: netlify
  - skill: git
  - skill: svn
  - skill: node
  - skill: postCSS
  - skill: YAML
  - skill: capistrano
  - skill: SSH
  - skill: PHP
  - skill: javascript
  - skill: agile
  - skill: gtd
  - skill: sublime text
  - skill: visual studio code
  - skill: boostrap 5

exclude: 
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - build
  - js
  - sass
include: ["_pages", "_redirects"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"

# Collections
collections:
  originalproductions:
    output: true
    permalink: /work/original-music-productions/:path/
  sounddesign:
    output: true
    permalink: /work/sound-design/:path/
  webdesign:
    output: true
    permalink: /work/web-design/:path/

# Taxonomy
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
  slug_mode: latin
  date: 2021-11-16 23:27:11

excerpt_separator: <!--more-->

# Responsive images
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
    - width: 768
    - width: 1200

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image