host: "localhost"
url: "https://minutestomidnight.co.uk"
baseurl: ""

# SEO
title: Minutes to Midnight
tagline: Sound and Web Designer
description: Minutes to Midnight is the moniker of music producer and frontend developer Simone Silvestroni.
permalink: /blog/:title/
keywords:
  sound design,
  bass player,
  game audio,
  music production,
  web design,
  web development,
  frontend
timezone: Europe/Rome
logo: /assets/images/m2m-og-image.jpg
author:
  name: Simone Silvestroni
  email: hello@minutestomidnight.co.uk

# Brand
brand:
  m2m_pitch: I&rsquo;m a liaison between creativity and logic.

exclude: 
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - build
  - js
  - sass
include: ["_pages", "_redirects"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"

# Collections
collections:
  originalmusicproductions:
    output: true
    permalink: /work/original-music-productions/:path/
  sounddesign:
    output: true
    permalink: /work/sound-design/:path/
  webdesign:
    output: true
    permalink: /work/web-design/:path/

# Taxonomy
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: cats-tags
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
  slug_mode: latin
  date: 2021-11-16 23:27:11

excerpt_separator: <!--more-->

# Responsive images
responsive_image:
  template: _includes/pattern-responsive-image.html
  sizes:
    - width: 576
    - width: 768
    - width: 1200

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-responsive-image