[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = '''
      max-age=31536000;
      includeSubDomains;
      preload
    '''
    Content-Security-Policy = '''
      default-src 'self';
      style-src 'self' 'unsafe-inline';
      img-src 'self';
      script-src 'self' https://s4.bcbits.com;
      frame-src https://yewtu.be/embed/ https://www.youtube-nocookie.com/embed/ https://bandcamp.com/EmbeddedPlayer/ https://player-widget.mixcloud.com/;
      object-src 'self';
      frame-ancestors 'self' https://ui.dev/amiresponsive;
    '''
    Permissions-Policy = '''
      accelerometer=(self),
      autoplay=(self),
      camera=(self),
      encrypted-media=(self),
      fullscreen=(self),
      geolocation=(self),
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      usb=(self),
      picture-in-picture=(self "https://yewtu.be/embed/" "https://www.youtube-nocookie.com/embed/")
    '''
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=15768000"