# -------------------
# Site settings
# -------------------
host: 'localhost'
url: 'https://minutestomidnight.co.uk'
baseurl: ''
destination: ../site
lang: 'en-GB'
title: 'Minutes to Midnight'
tagline: 'Web designer & music producer'
timezone: Europe/London
logo: '/assets/images/m2m-og-image.png'
typeface: 'Rubik, with a touch of serif'
typeface-preload: 'rubik-regular.woff2'
jekyll-version: '4.3.3'

# -------------------
# Personal data
# -------------------
author:
  name: 'Simone Silvestroni'
  givenName: 'Simone'
  familyName: 'Silvestroni'
  email: 'hello@minutestomidnight.co.uk'
mastodon:
  instance: sonomu.club
  username: m2m

# -------------------
# Online profiles
# -------------------
link:
  - name: Email
    label: hello@minutestomidnight.co.uk
    url: mailto:hello@minutestomidnight.co.uk
  - name: GitHub
    label: https://github.com/simonesilvestroni
    url: https://github.com/simonesilvestroni
  - name: LinkedIn
    label: https://www.linkedin.com/in/simonesilvestroni
    url: https://www.linkedin.com/in/simonesilvestroni
  - name: Bandcamp
    label: https://minutestomidnight.bandcamp.com
    url: https://minutestomidnight.bandcamp.com
  - name: YouTube
    label: https://www.youtube.com/@m2m
    url: https://www.youtube.com/@m2m

# -------------------
# About
# -------------------
description: "A gen X with a straight to the point attitude. Based in the UK, I play bass and design sound under the moniker Minutes to Midnight."
keywords:
  minutes to midnight,
  simone silvestroni,
  sound design,
  bass,
  game audio,
  foley,
  field recording,
  music production,
  music composer,
  mix,
  master,
  reaper,
  pro tools,
  logic pro,
  web design,
  web development,
  web performance,
  web accessibility,
  web usability,
  front-end,
  ux,
  user experience,
  jekyll,
  wordpress,
  html,
  css

# -------------------
# Inclusions
# -------------------
include: ["_pages"]

# -------------------
# SASS
# -------------------
sass:
  sass_dir: /assets/css/partials/
  sourcemap: development

# -------------------
# Feeds
# -------------------
posts_limit: 20

# -------------------
# Jekyll defaults
# -------------------
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# -------------------
# Jekyll archives
# -------------------
jekyll-archives:
  enabled:
    - tags
  layout: tags
  permalinks:
    tag: '/blog/tag/:name/'
  slug_mode: latin

# -------------------
# Markdown
# -------------------
kramdown:
  syntax_highlighter_opts:
    disable: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

# -------------------
# Jekyll plugins
# -------------------
plugins:
  - jekyll-archives